builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    hooks:
      pre:
        - make gen_version
